import type { Metadata } from 'next';
import AppLayout from '@/shared/layouts/AppLayout';
import './global.css';
import { QueryClientProvider } from '@/shared/providers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function Qna({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <QueryClientProvider>
          <AppLayout header footer floating>
            {children}
          </AppLayout>
        </QueryClientProvider>
      </body>
    </html>
  );
}
