import type { Metadata } from 'next';
import ReactQueryProviders from './(hooks)/useReactQuery';
import Chatting from './(components)/common/Chatting';
import ScrollUp from './(components)/common/ScrollUp';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ReactQueryProviders>
          {children}
          <Chatting />
          <ScrollUp />
        </ReactQueryProviders>
      </body>
    </html>
  );
}
